FROM eclipse-temurin:17-jdk as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw install -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /workspace/app
ENV PORT 8080
EXPOSE 8080

COPY --from=build /workspace/app/target/*.war /workspace/app/app.war

ENTRYPOINT exec java $JAVA_OPTS -jar app.war
