# Simple → Run without credit institute, payment is disabled
version: "3"
services:
  modulith:
    container_name: t2-modulith
    image: t2project/modulith:main
    ports:
      - "8081:8080"
    depends_on:
      - mongo
      - postgres
    environment:
      MONGO_HOST: mongo
      T2_INVENTORY_SIZE: "25"
      T2_PAYMENT_PROVIDER_ENABLED: false
      T2_PAYMENT_PROVIDER_DUMMY_URL: http://dummy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_PROFILES_ACTIVE: docker

  mongo:
    container_name: t2-mongo
    image: mongo:5.0
    ports:
      - "27017:27017"

  postgres:
    container_name: t2-postgres
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  jmeter:
    container_name: t2-jmeter
    image: t2project/jmeter:5.6.2
    environment:
      JVM_XMN: 100 # maximum nursery size
      JVM_XMS: 250 # initial heap size
      JVM_XMX: 500 # maximum heap size
    # command: >
    #   -Dlog_level.jmeter=DEBUG
    #   -Jhostname=t2-modulith
    #   -Jport=8080
    #   -JnumUser=10
    #   -JrampUp=2
    #   -JthinkTimeTimeout=3000
    #   -JthinkTimeRange=3000
    #   -JstartDelayTime=10000
    #   -n -t /tests/t2-project-fixed-single-delayed-start.jmx
    #   -l /tests/results.csv
    #   -j /jmeter.log
    #   -e -o /tests/report -f
    volumes:
      - ./usage_scenarios/jmeter:/tests
