---
version: "2"
services:
  modulith:
    container_name: t2-modulith
    image: t2project/modulith:main
    depends_on:
      - mongo
      - postgres
    environment:
      MONGO_HOST: mongo
      POSTGRES_HOST: postgres
      SPRING_PROFILES_ACTIVE: gmt
    networks:
      - t2-network
  mongo:
    container_name: t2-mongo
    image: mongo:5.0
    networks:
      - t2-network
  postgres:
    container_name: t2-postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - t2-network

networks:
  t2-network:
